### ISSUE TITLE
extractor & Windows

### ISSUE THREAD

**Issue by plebreton** [itu-p1203/itu-p1203#11]
Hello,

I had a look at how the extractor run on windows, and I saw some issues. 

First I saw that lines 400-406, that you use the shell to get file size:
`cmd = "stat -f '%z' '{segment}'"`

But something more portable could be used by sticking to Python like:
`segment_size = os.path.getsize(segment)`

On macOS both approaches return the same, so I would suggest to use the portable way. Or there was a reason that I am missing?

The second thing I saw which breaks Windows compatibility was the use of quotation mark ' line 408:
`cmd = "ffprobe -loglevel error -show_streams -show_format -of json '{segment}'" `

Maybe something like this could be done instead:
`cmd = "ffprobe -loglevel error -show_format -of json '{segment}'"`
` if os.name == 'nt':`
`    cmd = "ffprobe -loglevel error -show_streams -show_format -of json {segment}"`

I understand the reason of using the (') to avoid issues with spaces, and I believe windows like better ("), but I had issues with that other quotation mark as well. So, I just removed it for windows... 

Note that for the sake of consistency in the handling of spaces in file names, you are missing quotation marks (') line 279 (when calling ffmpeg_debug_qp).

And then, with that done, I had it working on Windows. 

I also made a windows build of ffmpeg_debug_qp. I can make a pull request for that if you want (VS2015 sln files and build), but I can understand that you don't want to commit at maintaining the windows build ;)

**Comment by slhck** [comment]
> But something more portable could be used by sticking to Python like: `segment_size = os.path.getsize(segment)`

Good suggestion!

>  Or there was a reason that I am missing?

Pure laziness and not wanting to deal with non-Unix systems.

> I understand the reason of using the (') to avoid issues with spaces, and I believe windows like better ("), but I had issues with that other quotation mark as well.

The better solution is to not build the command as a space-separated string, but with a list of arguments. This way, all the quoting is done by Python. I can re-write the command-line calls.

> I also made a windows build of ffmpeg_debug_qp. I can make a pull request for that if you want (VS2015 sln files and build)

That would be much appreciated! The program's code hasn't really changed since we originally released it, so there's no big maintenance burden. (If at some point future codecs get added, ffmpeg will likely not work anymore anyway, since the program relies on an undocumented hack.)

**Comment by slhck** [comment]
This should be fixed in 1.2.8, could you please test?

**Comment by plebreton** [comment]
I just checked, it is working :)
