### ISSUE TITLE
Pv mode 0 on different resolutions

### ISSUE THREAD

**Issue by psacoustic** [itu-p1203/itu-p1203#30]
I tried to plot some mode 0 curves with different resolutions given a device display resolution of 1080p. It doesn't make sense to me, as I was expecting some cross-over between different resolutions - think about a convex hull of ABR ladder. Is there any limitation, such as a certain resolution cannot be less than some value (e.g., I cannot think of 10 kbits/s of 1080p taking 2.75 MOS for h.264)? 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/17693354/184524222-7546aad8-1c4f-49b2-ab36-cc3d96443dc7.png">

**Comment by slhck** [comment]
Thanks for your comment! This is actually a known limitation with the P.1203.1 model, which partly stems from the fact that during development, the range of bitrates/resolutions had to be limited, and, consequently, extrapolations beyond the tested range were not performed.

These values are in P.1203.1 Table 1-1:

| Resolution | Bitrate |
| ---------- | ------------ |
| 240p | 75-150 kbit/s |
| 360p | 220-450 kbit/s |
| 480p | 375-750 kbit/s |
| 720p | 1050-2100 kbit/s |
| 1080p | 1875-12500 kbit/s |

This means that when it comes to measuring the quality of ABR ladders — or even optimizing them —, using P.1203.1 Mode 0 is not a good solution. The model performs reasonably well in the context of predicting the QoE of longer sessions (in the range of minutes), where quality is impacted more by temporal fluctuations and stalling.

When it comes to assessing the quality of encoded video without a reference, the standardized [P.1204.3 model](https://github.com/Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3), which is bitstream-based (i.e., it requires bitstream access), performs *much* better.

That said, P.1204.3 cannot be used in a Mode 0 context where only codec/resolution/bitrate/framerate is known. No official P.1204 Mode 0 model exists, unfortunately. A non-official version [is available here](https://github.com/Telecommunication-Telemedia-Assessment/p1204_3_extensions). This uses the core functions of P.1204.3 under the hood. It should work much better than P.1203.1 Mode 0.

**Comment by psacoustic** [comment]
Thank you for pointing out the table for the range of bitrates the model has been validated. That's what I was looking for. 

I understand temporal fluctuation impacts subjective scores and limits the scope of objective model modes. If there is no temporal effect (bitrate switching, stalling, etc) and there's a purely bitrate and resolution conditions in the data set, what accuracies should I expect from the mode 0? Are there any literature for that?

One more question. Would the non-official version of 1204.3 mode 0 covers all the resolutions equal to or less than 1080p as well?

**Comment by slhck** [comment]
> I understand temporal fluctuation impacts subjective scores and limits the scope of objective model modes. If there is no temporal effect (bitrate switching, stalling, etc) and there's a purely bitrate and resolution conditions in the data set, what accuracies should I expect from the mode 0? Are there any literature for that?

As far as I am aware, there have been no studies made on conditions without HAS-type artifacts. I would really see the P.1203.1 Mode 0 model as a tool to *approximate* the per-second video quality, keeping in mind that the real quality will depend on factos that a metadata-based model cannot incorporate, like content type and encoder settings/efficiency. For this you would have to at least use a Mode 1 model (taking into account frame types and sizes to gauge content complexity), or a Mode 3 model which directly looks at encoding parameters (like motion vectors and QP).

> One more question. Would the non-official version of 1204.3 mode 0 covers all the resolutions equal to or less than 1080p as well?

All models from P.1204, including P.1204.3 Mode 0, cover resolutions from 240p up to 2160p.

**Comment by psacoustic** [comment]
Thanks. Completely agree that the mode 0 is a quite limited model. But it is true that there are also use cases where the mode 0 is the only choice as no extra data logging is available. It would have been better if ITU-T shared better information as an amendment at least for the performance of mode 0 for the "in-scope" conditions (assuming temporal quality variability is one of out-of-scope of the mode 0), instead of overall correlation on the databases used in the model development.

**Comment by slhck** [comment]
I absolutely understand that. While the number of databases for developing the model was quite large, most of them are not publicly sharable due to non-disclosure agreements between the creators. 

We've published a [subset of the databases](https://github.com/itu-p1203/open-dataset) with all scores, so this type of evaluation could be done on those sequences, but there are only few “reference” type conditions without quality variations.

**Comment by slhck** [comment]
Coming back to this I just want to underline the better performance of the P.1204.3-based “bitstream mode 0”: https://github.com/Telecommunication-Telemedia-Assessment/p1204_3_extensions/blob/master/bitstream_mode0/README.md

You can see the behavior of typical bitrates for the different codecs here:

![image](https://user-images.githubusercontent.com/582444/234490168-a84a36d2-16c7-4280-86f0-d5acde986f23.png)

Top shows the existing P.1203.1 Pv model (with custom coefficients for non-H.264 codecs), bottom shows the new model as available on GitHub. So you can get a better prediction accuracy when plugging in this instead of P.1203.1, e.g. by having it predict the MOS values per-second before, and then feeding them into the `O22` list for the P.1203. input report.

I will close this issue for now, as for this reference implementation there isn't much that can be done.
