### ISSUE TITLE
Why Random Forest is being used?

### ISSUE THREAD

**Issue by Ayushi-0803** [itu-p1203/itu-p1203#37]
Can u please tell me why u have used the random forest model only and not any other model?
Did you try out with other models?

**Comment by slhck** [comment]
The Random Forest part was a contribution of one member of ITU-T submitting this as a candidate model for the overall integration (Pq) module. Using it achieved a better overall performance than without it, since it captures variability in the dataset that the analytical (formula-based) part cannot. That said, I do not know whether that ITU-T member had tried different machine learning techniques. I am sure they had a good reason to pick Random Forests due to their generally favorable performance and adaptibility.

**Comment by Ayushi-0803** [comment]
okay ..thanks a lot...but can you tell that why only 20 decision trees were used in the Random Forest model?

**Comment by slhck** [comment]
Sorry for the late reply. The ITU contributor who trained the model may have tried different parameterizations of the RF but ended up using this one because it gave the best internal performance on a training/test split.
